# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdivide <- function(properties, bin_min, bin_max, nbins) {
    .Call(`_designtools_bdivide`, properties, bin_min, bin_max, nbins)
}

perm_bdivide <- function(properties, bin_min, bin_max, nbins, max_iter = 25000L, t_amp = 4000, t_center = 0, t_width = 3000) {
    .Call(`_designtools_perm_bdivide`, properties, bin_min, bin_max, nbins, max_iter, t_amp, t_center, t_width)
}

perm_bdivide2 <- function(n_nit, properties, bin_opt, nbins, max_iter = 25000L, t_amp = 4000, t_center = 0, t_width = 3000) {
    .Call(`_designtools_perm_bdivide2`, n_nit, properties, bin_opt, nbins, max_iter, t_amp, t_center, t_width)
}

bdivide2 <- function(nit, properties, bin_opt, nbins) {
    .Call(`_designtools_bdivide2`, nit, properties, bin_opt, nbins)
}

kmk_partition <- function(nrs, k) {
    .Call(`_designtools_kmk_partition`, nrs, k)
}

tsp_complete <- function(m) {
    .Call(`_designtools_tsp_complete`, m)
}

tsp_complete2 <- function(m) {
    .Call(`_designtools_tsp_complete2`, m)
}

tsp_sa <- function(m, max_iter = 25000L, t_amp = 4000, t_center = 0, t_width = 3000) {
    .Call(`_designtools_tsp_sa`, m, max_iter, t_amp, t_center, t_width)
}

